# **************************************************************************** #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:ipoij +:+         +:+      #
#    By: frocha-b <frocha-b@student.42porto.co      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/07 12:40:22 by frocha-b          #+#    #+#              #
#    Updated: 2025/04/07 13:04:55 by frocha-b         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = ft_display_file
CC = cc
CFLAGS = -Wall -Werror -Wextra
SRCS = ft_display_file.c
all: $(NAME)

$(NAME) : $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o $(NAME) 
clean:

fclean: clean
	rm -f $(NAME)	
